import 'package:trading_demo_app/features/trading/data/models/stock_model.dart';

const List<StockModel> watchlist1Data = [
  StockModel(
    id: 'w1_1',
    name: 'RELIANCE',
    symbol: 'NSE | EQ',
    exchange: Exchange.nse,
    type: StockType.eq,
    price: 1374.00,
    change: -4.50,
    changePercent: -0.33,
  ),
  StockModel(
    id: 'w1_2',
    name: 'HDFCBANK',
    symbol: 'NSE | EQ',
    exchange: Exchange.nse,
    type: StockType.eq,
    price: 966.85,
    change: 0.85,
    changePercent: 0.09,
  ),
  StockModel(
    id: 'w1_3',
    name: 'ASIANPAINT',
    symbol: 'NSE | EQ',
    exchange: Exchange.nse,
    type: StockType.eq,
    price: 2537.40,
    change: 6.60,
    changePercent: 0.26,
  ),
  StockModel(
    id: 'w1_4',
    name: 'NIFTY IT',
    symbol: 'IDX',
    exchange: Exchange.indexExchange,
    type: StockType.idx,
    price: 35187.55,
    change: 877.11,
    changePercent: 2.56,
  ),
  StockModel(
    id: 'w1_5',
    name: 'RELIANCE SEP 1880 CE',
    symbol: 'NSE | Monthly',
    exchange: Exchange.nse,
    type: StockType.option,
    price: 0.00,
    change: 0.00,
    changePercent: 0.00,
  ),
  StockModel(
    id: 'w1_6',
    name: 'RELIANCE SEP 1370 PE',
    symbol: 'NSE | Monthly',
    exchange: Exchange.nse,
    type: StockType.option,
    price: 19.20,
    change: 1.00,
    changePercent: 5.49,
  ),
  StockModel(
    id: 'w1_7',
    name: 'MRF',
    symbol: 'NSE | EQ',
    exchange: Exchange.nse,
    type: StockType.eq,
    price: 147625.00,
    change: 550.00,
    changePercent: 0.37,
  ),
  StockModel(
    id: 'w1_8',
    name: 'MRF',
    symbol: 'BSE | EQ',
    exchange: Exchange.bse,
    type: StockType.eq,
    price: 147439.45,
    change: 463.80,
    changePercent: 0.32,
  ),
];
