import 'package:trading_demo_app/features/trading/data/models/stock_model.dart';

const List<StockModel> watchlist5Data = [
  StockModel(
    id: 'w5_1',
    name: 'TCS',
    symbol: 'NSE | EQ',
    exchange: Exchange.nse,
    type: StockType.eq,
    price: 4123.80,
    change: 45.70,
    changePercent: 1.12,
  ),
  StockModel(
    id: 'w5_2',
    name: 'INFY',
    symbol: 'NSE | EQ',
    exchange: Exchange.nse,
    type: StockType.eq,
    price: 1554.25,
    change: -12.40,
    changePercent: -0.79,
  ),
  StockModel(
    id: 'w5_3',
    name: 'ICICIBANK',
    symbol: 'NSE | EQ',
    exchange: Exchange.nse,
    type: StockType.eq,
    price: 1188.90,
    change: 8.20,
    changePercent: 0.69,
  ),
  StockModel(
    id: 'w5_4',
    name: 'NIFTY 50',
    symbol: 'IDX',
    exchange: Exchange.indexExchange,
    type: StockType.idx,
    price: 22451.35,
    change: 36.20,
    changePercent: 0.16,
  ),
  StockModel(
    id: 'w5_5',
    name: 'SBIN',
    symbol: 'NSE | EQ',
    exchange: Exchange.nse,
    type: StockType.eq,
    price: 808.60,
    change: -4.10,
    changePercent: -0.50,
  ),
  StockModel(
    id: 'w5_6',
    name: 'BANKNIFTY SEP 48000 CE',
    symbol: 'NSE | Monthly',
    exchange: Exchange.nse,
    type: StockType.option,
    price: 245.40,
    change: 18.20,
    changePercent: 8.01,
  ),
];
