import 'package:trading_demo_app/features/trading/data/models/stock_model.dart';

const List<StockModel> watchlist6Data = [
  StockModel(
    id: 'w6_1',
    name: 'BAJFINANCE',
    symbol: 'NSE | EQ',
    exchange: Exchange.nse,
    type: StockType.eq,
    price: 7235.55,
    change: 88.40,
    changePercent: 1.24,
  ),
  StockModel(
    id: 'w6_2',
    name: 'HINDUNILVR',
    symbol: 'NSE | EQ',
    exchange: Exchange.nse,
    type: StockType.eq,
    price: 2430.10,
    change: -21.35,
    changePercent: -0.87,
  ),
  StockModel(
    id: 'w6_3',
    name: 'LT',
    symbol: 'NSE | EQ',
    exchange: Exchange.nse,
    type: StockType.eq,
    price: 3598.90,
    change: 9.80,
    changePercent: 0.27,
  ),
  StockModel(
    id: 'w6_4',
    name: 'SENSEX',
    symbol: 'IDX',
    exchange: Exchange.indexExchange,
    type: StockType.idx,
    price: 73112.41,
    change: -145.30,
    changePercent: -0.20,
  ),
  StockModel(
    id: 'w6_5',
    name: 'TATAMOTORS',
    symbol: 'NSE | EQ',
    exchange: Exchange.nse,
    type: StockType.eq,
    price: 1026.75,
    change: 14.55,
    changePercent: 1.44,
  ),
  StockModel(
    id: 'w6_6',
    name: 'NIFTY SEP 22500 PE',
    symbol: 'NSE | Monthly',
    exchange: Exchange.nse,
    type: StockType.option,
    price: 134.85,
    change: -6.15,
    changePercent: -4.36,
  ),
];
